name: "Wrap"

on:
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Run in all these versions of Python
        python-version: ["3.10"]

    steps:
        # Checkout the latest code from the repo
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

        # Setup which version of Python to use
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

        # Display the Python version being used
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

        # Update pip
      - name: Update pip
        run: python -m pip install --upgrade pip

        # Install requirements.
      - name: Install requirements
        run: python -m pip install --upgrade -r requirements.txt

        # Detect changed files
      - name: Detect changed files
        run: echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }}) -- $(find . -name *.po)" >> $GITHUB_ENV
        run: echo "${CHANGED_FILES}"
      #   # Wrap changed files
      # - name: Wrap
      #   run: |
      #     if #${CHANGED_FILES}[@] == 0; then
      #       echo "No files to wrap"
      #     else
      #       echo "Wrapping files: ${CHANGED_FILES}"
      #       for file in ${{ CHANGED_FILES }}; do
      #         echo "Wrapping $file"
      #         powrap $file
      #       done
      #     fi